name: tapkar_ai
description: "TapKar AI — Bas tap karo, AI sab kar dega."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  speech_to_text: ^7.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  image_picker: ^1.1.2
  audioplayers: ^6.6.0
  flutter_local_notifications: ^21.0.0
  record: ^6.2.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
